# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- script: |
    npm install -g lerna
    lerna bootstrap --hoist
  name: 'install'
  displayName: 'npm install and bootstrap'
- script: |
    npm run build
  name: 'build'
  displayName: 'npm build'
- script: |
    npm run npmrc -- registry=$(registry)
  name: 'set_registry'
  displayName: 'Prepare regtistry in .npmrc for Publish'
- task: npmAuthenticate@0
  inputs:
    workingFile: '.npmrc'
  name: 'auth_registry'
  displayName: 'Login to Registry'
- script: |
    lerna publish prerelease --no-push --force-publish --no-git-tag-version --registry $(registry) --yes
  name: 'publish'
  displayName: 'Publish to Registry'
